version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    expose:
      - "4000"
    command:
      - "--server-addr=:4000"
      - "--redis-addr=redis:6379"
      - "--mongo-addr=mongodb://mongo:27017"
    depends_on:
      - redis
      - mongo
      - prometheus
  judge:
    build:
      context: .
      dockerfile: ./docker/judge/Dockerfile
    command:
      - "--workers=1000"
      - "--redis-addr=redis:6379"
      - "--mongo-addr=mongodb://mongo:27017"
    depends_on:
      - redis
      - mongo
  judgemon:
    build:
      context: .
      dockerfile: docker/judgemon/Dockerfile
    command:
      - "--redis-addr=redis:6379"
      - "--enable-metrics-exporter=true"
      - "--prometheus-addr=http://prometheus:9090"
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
      - redis
      - mongo
  prometheus:
    build:
      context: .
      dockerfile: docker/prometheus/Dockerfile
    ports:
      - "9090:9090"
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    expose:
      - "6379"
  mongo:
    build:
      context: .
      dockerfile: docker/mongo/Dockerfile
    ports:
      - "27017:27017"
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - judgemon
      - prometheus
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
